### ISSUE TITLE
[Bug]: Exception with "Ui.invokeStringA" function

### ISSUE THREAD

**Issue by ikt28** [skyrim-multiplayer/skymp#1007]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Not just "Ui.invokeStringA", all invoke array functions in Ui class have this error.
These functions seems not working and this appear in console `[Exception] Unsupported Javascript type (8)`

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

9a4bb6b

### server commit''s hash

N/A

### Videocard model

GTX 1060

### Steps to reproduce

This is part of my test script
"wheelmenu" is from [UIExtensions](https://www.nexusmods.com/skyrimspecialedition/mods/17561)
```
let b = 0
on('update', () => {
   if (sp.Input.isKeyPressed(48) && b == 0){
      sp.Ui.openCustomMenu("wheelmenu", 0)
      b = 1
   }
});

on('menuOpen', (e) => {
   if (e.name == "CustomMenu"){
      const s = ["", "", "", "", "", "", "", ""]
      sp.Ui.invokeStringA("CustomMenu", "_root.WheelPhase.WheelBase.setWheelOptionLabels", s)
   }		
});

on('menuClose', (e) => {
   if (e.name == "CustomMenu"){
      b = 0
   }		
});
```

### Expected result

`[Exception] Unsupported Javascript type (8)`

### Actual result

The WheelMenu UI show up without problem but invoke array to use swf file actionscript function is not working

**Comment by Pospelove** [comment]
Arrays are currently not supported here :(
