### ISSUE TITLE
Papyrus VM assistance

### ISSUE THREAD

**Issue by donaldkeykong** [skyrim-multiplayer/skymp#1027]
I am with a group looking for assistance with creating a Papyrus VM for a very similar project (Not Skyrim) in C#.
Would anyone in this project be interested in helping us?

**Comment by Pospelove** [comment]
@donaldkeykong We can probably just plug our Papyrus VM which is publicly available into your project, you can write me in Discord: Pospelov#3228

**Comment by donaldkeykong** [comment]
thanks, sent you a friend request
