### ISSUE TITLE
[Bug]: CTDs when fighting spriggans

### ISSUE THREAD

**Issue by duffbeeeer** [skyrim-multiplayer/skymp#1112]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

In combination with TrueHUD SP 2.6 seem to crash when getting close to spriggans.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.08

### SKSE version

2.0.15

### client commit''s hash

-

### server commit''s hash

-

### Videocard model

3090

### Steps to reproduce

1. Install latest SP 2.6 and TrueHUD
2. go near a spriggan
3. CTD

I have tried it with SP 2.5 as well and the crash is not happening.

I lost my log somewhere, sorry for that. Multiple users are also reporting this issue. 

### Expected result

Should not CTD

### Actual result

Crash

**Comment by objir** [comment]
On my end, there are no more crashes IF:
1. Spawn a spriggan right next to the player.
2. With SP 2.6 activated BUT loads no js plugins.

**Comment by duffbeeeer** [comment]
Kingfish managed to find the root cause and made a patch to disable the problematic magic effect for now. Proper fix still needs to implemented.

https://www.nexusmods.com/skyrimspecialedition/mods/69363
