### ISSUE TITLE
[Bug]: High CPU usage by Skyrim Platform

### ISSUE THREAD

**Issue by opsetech** [skyrim-multiplayer/skymp#1199]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

Skyrim Platform 100% CPU Usage even in main menu.
No extra mods installed.

### OS

Windows

### OS version

11

### Skyrim version

1.6.353

### SKSE version

2.1.5

### client commit''s hash

None

### server commit''s hash

None

### Videocard model

Nvidia 1050 Ti

### Steps to reproduce

install Skyrim Platform.

### Expected result

No CPU usage difference between Skyrim Platform and Address Library , at least in main menu.

### Actual result

High CPU usage even in main menu.

**Comment by opsetech** [comment]
PC SPECS:
Intel i5-6600K
RAM: 24GB @ 3200Mhz
Storage: 1TB NVME

**Comment by axet** [comment]
I can say the same. Skyrim Platfrom eats 100% cpu in main menu and the game.

* SkyrimSE.exe version 1.6.659.0
* Skyrim Platform 2.7.1 (Anniversary Edition)

**Comment by Pospelove** [comment]
I'm sorry, we're not able to reproduce this. It's probably one of skyrim platform plugins fault. (I don't think you use SP without any plugins)
