### ISSUE TITLE
Error Bad form ID when looting container

### ISSUE THREAD

**Issue by alekcey0211** [skyrim-multiplayer/skymp#120]
I went to qasmoke test location.
Here are its coordinates to move for testing.
```json
"qasmoke": {
  "pos": [-751.9232177734375, 1747.129638671875, 6976.00048828125],
  "angle": [0, 0, 47],
  "worldOrCellDesc": "32ae7:Skyrim.esm"
}
```
When I try to loot one of the Dragonborn add-on chests, I see this error in the game console `Bad form ID 20291f4`
There are a lot of such errors, apparently for each item in the container.

Mods load order from server
```json
"loadOrder": [
  "Skyrim.esm",
  "Update.esm",
  "Dawnguard.esm",
  "HearthFires.esm",
  "Dragonborn.esm"
]
```

**Comment by Cazexotono** [comment]
All content associated with Hearthfire and Dragonborn DLC (excluding Dawnguard) causes various problems when interacting with these DLC items. This may be due to incorrect assignment of XX sequence number to the DLC.

**Comment by Pospelove** [comment]
Closing all "temporary unsupported"
