### ISSUE TITLE
Create server settings to manage CEF remote_debugging_port = 9000

### ISSUE THREAD

**Issue by alekcey0211** [skyrim-multiplayer/skymp#124]
When you log on to someone's server, then you can safely log on to localhost:9000 locally and put the server by sending a bunch of large messages to the chat.
Is it possible to make a setting so that this can be turned off in the production version

**Comment by Pospelove** [comment]
Technically we could disable Chromium devtools at all. But imagine one user brings back this feature and builds the project from sources? I want to say this is a server-side issue and attempts to fix it on the client-side will fail.

**Comment by alekcey0211** [comment]
Yes, I agree, I think you need to make protection on the server. Let's block requests with different origin or requests from localhost
