### ISSUE TITLE
Minimize catch2 includes

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#1265]
In #1228, `catch2/catch.hpp` includes were replaced with `catch2/catch_all.hpp`. Looks like it made build times a bit(?) worse.

We need to replace them with more minimal set of includes. Probably in most cases it's `catch2/catch_test_macros.hpp` + sometimes some include for `ContainsSubstring`

**Comment by Pospelove** [comment]
won't fix. please feel free to reopen if you willing to work on that
