### ISSUE TITLE
Send msgpack instead of plain-text JSON over network

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#127]
Currently, JSON data in text format is sent over network. We could replace it with binary format (https://msgpack.org/) everywhere (`nlohmann::json` has builtin support for msgpack).

(Preferably, we should replace as much as possible with schemaful binary format, but that isn't possible everywhere)

- [ ] Replace simdjson with nlohmann + msgpack
- [ ] Remove Read/ReadEx utils from mp_common, simdjson from vcpkg.json and CMake

**Comment by Pospelove** [comment]
Using msgpack with nlohmann::json would **increase parse time**. But it also would save ~30% of net traffic and would allow us to drop the simdjson dependency.

**Comment by Pospelove** [comment]
We should do it after merging the binary movement format to parse movement messages fast on the server.

**Comment by Pospelove** [comment]
It requires a lot of work and will slow down packet parsing on the server. We're better should switch to our own binary format where needed. Feel free to reopen later if we go back to this.
