### ISSUE TITLE
Add usable docker image

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#1325]
To use the latest stable version, run

`
docker run -d -it -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
`

Oops. This is [minecraft-server](https://github.com/itzg/docker-minecraft-server/blob/master/README.md). I wish we had such a feature here!

We should enable standard Docker workflow: docker build + docker run = running server.
And nothing else is required.

Bonus points if we also will be careful about layers. Build heavy parts first. Do not make heavy parts dependent on frequently changing source files and/or configs.

**Comment by szymonj99** [comment]
I can potentially look into this; not a guarantee though, as I'm a little busy with some other work. 💯

**Comment by Pospelove** [comment]
@szymonj99 you're welcome 
you can take a look at https://github.com/skyrim-multiplayer/skymp/pull/1343 for reference

**Comment by Pospelove** [comment]
won't fix
