### ISSUE TITLE
[Bug]: Calling Papyrus method Game.DisablePlayerControls causes game to hang, when abMovement = true

### ISSUE THREAD

**Issue by freed00m21** [skyrim-multiplayer/skymp#1329]
I'm calling this Papyrus method from server-side like this:
```
mp.callPapyrusFunction(
  'global',
  'Skymp',
  'SetDefaultActor',
  null,
  [{ type: 'form', desc: mp.getDescFromId(actorId) }]
);
mp.callPapyrusFunction(
  'global',
  'Game',
  'DisablePlayerControls',
  null,
  [true, true, true, true, true, true, true, true, 0]
);
```

This results in client game totally hang. And it's not a segfault, in debugger it looks like threads just waits until something happens.
When first argument abMovement = false, hang doesn't happens.

**Comment by Pospelove** [comment]
Hi, thanks for reporting this. Fixed in main branch as I remember. please feel free to reopen if still an issue
