### ISSUE TITLE
Implement asynchronous SP snippet requests from TypeScript

### ISSUE THREAD

**Issue by freed00m21** [skyrim-multiplayer/skymp#1342]
It works from C++ guest lib, but unfortunately we can't do it on TypeScript side. I seen that there is some fundament for this, but it's unfinished, right?
https://github.com/skyrim-multiplayer/skymp/blob/99099a8af7727cb26a42076e8f6e7bfc8aa25ce8/skymp5-server/cpp/addon/main.cc#L793-L810

**Comment by Pospelove** [comment]
I think this is by design, I don't think we should expose sp snippet, at least for now. we should better support vanila papyrus functions instead. but thanks for posting this!
