### ISSUE TITLE
Cmake warnings

### ISSUE THREAD

**Issue by sherlok235** [skyrim-multiplayer/skymp#139]
**I also have received something similar with these  https://github.com/skyrim-multiplayer/skymp/issues/80#issue-947129733  but on Linux**

> CMake Warning at cmake/add_papyrus_library_ck.cmake:37 (message):
> Missing Papyrus Compiler at OFF/Papyrus compiler/PapyrusCompiler.exe.
> Target skymp5-scripts wouldn't be built
> Call Stack (most recent call first):
> skymp5-scripts/CMakeLists.txt:5 (add_papyrus_library_ck)
> 
> CMake Warning at skymp5-server/cpp/CMakeLists.txt:114 (message):
> SKYRIM_DIR is not specified, Papyrus sources will not be built
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::mongoc_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::bson_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::mongoc_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::bson_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::mongoc_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::bson_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::mongoc_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
> This CMake target is deprecated. Use 'mongo::bson_static' instead.
> Consult the example projects for further details.
> Call Stack (most recent call first):
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
> vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
> skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> info TOOL Using Ninja generator, because ninja is available.
> info CMD CONFIGURE
>

**Comment by nic11** [comment]
As far as I can see, these warnings are the same. The only new warnings are:
```
CMake Warning at cmake/add_papyrus_library_ck.cmake:37 (message):
  Missing Papyrus Compiler at OFF/Papyrus compiler/PapyrusCompiler.exe.
Target skymp5-scripts wouldn't be built
Call Stack (most recent call first):
  skymp5-scripts/CMakeLists.txt:5 (add_papyrus_library_ck)

CMake Warning at skymp5-server/cpp/CMakeLists.txt:114 (message):
  SKYRIM_DIR is not specified, Papyrus sources will not be built
```

But this is expected. It's because of the following reasons:
1. Compiling Papyrus sources requires Bethesda's compiler from Creation Kit and is unsupported on Linux
2. You did not specify `SKYRIM_DIR` and/or it does not contain Creation Kit

When Creation Kit is not available, prebuilt scripts are used: https://github.com/skyrim-multiplayer/skymp/tree/main/skymp5-scripts/pex

So that works just fine unless you modify `.psc` files.

Created #140 for future improvements in this matter.
