### ISSUE TITLE
[Bug]: Error 126 after installing the Skyrim platform AE

### ISSUE THREAD

**Issue by alexsl2174** [skyrim-multiplayer/skymp#1423]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

Hi i'm playing using a mod that required this mod for Skyrim Together usage. But when I open Skyrim together before with the SE version (or the last one before AE) it said it wasn't compatible with 1.6.64 when I started the game so I coudn't proceed furter. Now that I have the AE version I don't have that message instead I get a error 126.

### OS

Windows

### OS version

10

### Skyrim version

1.6.64

### SKSE version

2.02

### client commit''s hash

i dont have that

### server commit''s hash

i dont have that

### Videocard model

NVIDIA GEforce 1060

### Steps to reproduce

After installing skyrim together and adding any mod that required Skyrim platform AE + their requirement you can start Skyrim together the bug will happen

### Expected result

Normaly I don't have any error and Skyrim Together just open and I can play

### Actual result

![image](https://github.com/skyrim-multiplayer/skymp/assets/79280782/424f47a0-f148-4553-a95d-02fdfc2ce038)
![image](https://github.com/skyrim-multiplayer/skymp/assets/79280782/316405fd-9a9c-4001-ada3-0f52b8cb2a82)

**Comment by Pospelove** [comment]
@alexsl2174 
Thank you for your report. You're using SP with SkyrimTogether, right? SP and ST conflict at this moment. You can't run both at the same time (since both mods use Chromium and even TiltedUI).

We may support SkyrimTogether compatibility in future updates.

Makes sense? :)

**Comment by Pospelove** [comment]
closing for now
