### ISSUE TITLE
Remove the disconnect message after reconnecting.

### ISSUE THREAD

**Issue by VitaliyMubarakov** [skyrim-multiplayer/skymp#1501]
![image](https://github.com/skyrim-multiplayer/skymp/assets/58411554/b8b50ac6-1521-4eb4-b112-924722c85e04)

**Comment by VitaliyMubarakov** [comment]
> @VitaliyMubarakov Thanks for posting this. could you please take a look?
> 
> I think we can destroy/hide this text in case of sp.mpClientPlugin.isConnected != false

After completing the current tasks, I will fix it.

**Comment by Pospelove** [comment]
moved this message to console. done.
