### ISSUE TITLE
Server crash when activate Furniture in Riverwood

### ISSUE THREAD

**Issue by alekcey0211** [skyrim-multiplayer/skymp#158]
It seems to me that after some of the updates, it began to paint after activating the chopping deck(0x6c3c9) in riverwood.
Very often the `RegisterForAnimationEvent` function is called and the server crashes.
```
[2021-08-30 08:42:07.097] [console] [warning] ResourceFurnitureScript: Method not found - 'RegisterForAnimationEvent'
[onActivate]  Error: Out of stack space
<unable to get stack>
```
if you delete this script, the problem will stop the server crash

**Comment by Pospelove** [comment]
Thanks for posting this :)

**Comment by Pospelove** [comment]
Closing all "temporary unsupported"
