### ISSUE TITLE
Problem with vcpkg on ubuntu after `..cmake` command

### ISSUE THREAD

**Issue by Richd4y** [skyrim-multiplayer/skymp#166]
![unknown](https://user-images.githubusercontent.com/69420236/132200999-8a4b4ecd-f076-4dae-8a25-3117c67d5891.png)

**Comment by nic11** [comment]
Run `cmake --version` please

**Comment by Richd4y** [comment]
CMake version is 3.21.2

**Comment by Pospelove** [comment]
@Richd4y Hey! Could you please tell us contents of this dir:
![image](https://user-images.githubusercontent.com/37947786/132208178-b2c92ff9-898e-4ff4-b660-b9749081b982.png)
Files, directories, etc

**Comment by Richd4y** [comment]
@Pospelove Sure!
![screenshot](https://user-images.githubusercontent.com/69420236/132210327-6f40d47a-066b-4858-94ab-7c3e3f0876f3.png)

**Comment by Richd4y** [comment]
![image](https://user-images.githubusercontent.com/69420236/132210468-45bfd512-1007-414b-8a3f-a980d01b1e74.png)

**Comment by Richd4y** [comment]
In 'out' i have only the "Debug" folder

**Comment by Pospelove** [comment]
@Richd4y Thanks. It seems your system has successfully built `libChakraCore.so` but failed to locate it after that.

Could you please try finding `libChakraCore.so` in `Debug/bin` or `Debug/lib`? If it isn't possible, please attach the `Debug` folder as an archive.

**Comment by Richd4y** [comment]
@Pospelove `libChakraCore.so` in the `Debug/bin/ChacraCore/`
![image](https://user-images.githubusercontent.com/69420236/132222970-532a23fb-713c-46ef-92a5-8f48f542fc03.png)

**Comment by Richd4y** [comment]
and there is another error on the screen

**Comment by Pospelove** [comment]
@Richd4y 
Test if this fix works for you #168

**Comment by Richd4y** [comment]
@Pospelove I updated and tried CMake again. But the mistakes remained the same.
![image](https://user-images.githubusercontent.com/69420236/132252417-4fb7cb7c-4512-4a44-8ad5-2f2cabc4b052.png)

**Comment by Pospelove** [comment]
> @Pospelove I updated and tried `cmake ..` again. But the mistakes remained the same.

@Richd4y I mean deleting repo from your machine and retrying from scratch with fix shipped. Did you do that?

**Comment by Richd4y** [comment]
[message.txt](https://github.com/skyrim-multiplayer/skymp/files/7121370/message.txt)
full log after `cmake ..`

**Comment by Pospelove** [comment]
Closing this issue after a private conversation in Discord. Everything generates successfully. If you are still able to reproduce, feel free to reopen this issue or open a new one.
