### ISSUE TITLE
[SP Bug]: cameraStateChanged event crashes the game when opening the map menu

### ISSUE THREAD

**Issue by Vorganger** [skyrim-multiplayer/skymp#1698]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

Using an on cameraStateChanged event in a SkyrimPlatform plugin and opening the map menu somehow causes a crash, regardless of what's in it. Of course, not using this event fixes the issue and could be worked around by using the on update event to check if the camera state has changed. However, using the on cameraStateChanged event would be preferred for performance reasons.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

None

### server commit''s hash

None

### Videocard model

RTX 2060

### Steps to reproduce

Have a SkyrimPlatform plugin that uses the on cameraStateChanged event. Nothing needs to be in it for the crash to occur. In-game, open the map menu and crash.

### Expected result

Opening the map menu does **not** crash the game.

### Actual result

Opening the map menu crashes the game.

**Comment by Pospelove** [comment]
Thank you for the report, I'll take a look
