### ISSUE TITLE
[SP Bug]: effectStart and/or effectFinish events crash the game when loading a save or main menu while fighting a mage

### ISSUE THREAD

**Issue by Vorganger** [skyrim-multiplayer/skymp#1711]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

Using an on effectStart and/or effectFinish event in a SkyrimPlatform plugin and loading a save or main menu while fighting a mage causes a crash, regardless of what's in it. While I could avoid this issue by not subscribing to those events, I actually want to use them in my plugin to determine if the player is a werewolf or vampire lord and I'm not aware of any possible workarounds.

Using SkyrimPlatform 2.8.0 with all dependencies installed.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

None

### server commit''s hash

None

### Videocard model

RTX 2060

### Steps to reproduce

Have a SkyrimPlatform plugin that uses the on effectStart and/or effectFinish events. Nothing needs to be in it for the crash to occur. In-game, be in a fight with a mage, load a save or main menu, and crash.

### Expected result

Loading a save or main menu while in a fight with a mage does **not** crash the game.

### Actual result

Loading a save or main menu while in a fight with a mage crashes the game.

**Comment by Vorganger** [comment]
I managed to workaround not needing those events to determine if the player is in beast/vampire lord form. I used the unequip event and checked if the player has the beast form and vampire lord form magic effects. Still, the issues regarding the effectStart and/or effectFinish effects will happen, but I won't need it for my plugin.

**Comment by Pospelove** [comment]
Thanks. I'll fix that
