### ISSUE TITLE
Papyrus compaibility

### ISSUE THREAD

**Issue by tarwich** [skyrim-multiplayer/skymp#1726]
First let me say thank you. Really SkyrimPlatform is really cool. I've written a few small mods like a stealth mod and rolling mod with it.

Is there any plan to be compatible with other Skryim Mods or call other Papyrus functionality in other mods? I'd like to start making my mod interoperate with other mods but I don't see a way. If this is something you plan on, never plan on, or possible to do, but I missed?

<details>
  <summary>MCM Example (just an example)</summary>

```papyrus
ScriptName MyModMCM extends MCM
{
    MCM_Menu myMenu

    Function RegisterMenu()
    {
        myMenu = MCM_Menu.Create("My Mod MCM")
        myMenu.AddHeader("My Mod MCM Header")
        myMenu.AddCheckbox("Option 1", "Option 1 Description", true)
        myMenu.AddSlider("Option 2", "Option 2 Description", 0, 100, 50)
        myMenu.AddDropdown("Option 3", "Option 3 Description", ["Option 3a", "Option 3b", "Option 3c"], 0)
        myMenu.Register()
    }

    Function OnPageReset()
    {
        myMenu.Reset()
    }

    Function OnSave()
    {
        myMenu.Save()
    }

    Function OnLoad()
    {
        myMenu.Load()
    }
}

ScriptName MyModMCMQuest extends Quest
{
    ObjectReference myObject

    Event OnActivate(ObjectReference akActionRef)
    {
        if (akActionRef == myObject)
        {
            MyModMCM.Show()
        }
    }
}
```

</details>

If this is a thing and you'd like me to make a real issue (bug report, feature request) I'm happy to do so. Just trying to figure out if I can call Papyrus functions from JS and if not, if it's ever going to be a thing, or if I'll have to essentially rewrite an other mod in Papyrus. Thanks!

**Comment by Pospelove** [comment]
Thank you so much!

I don't think there is a good way to do that ATM. People typically use JContainers because of being able to write/read values from both JavaScript/Papyrus

Also, there is SendModEvent that can be fired on the SkyrimPlatform side and caught on the Papyrus side.

If you have a good idea of how more straight-forward integration could look like, please feel free to write it here

**Comment by Pospelove** [comment]
please feel free to add something or reopen issue if you have anything else to add

**Comment by tarwich** [comment]
Yup. It'll take a while to come up with an integration. In the meantime I'm seeing what I can write without those. Thanks, man!
