### ISSUE TITLE
where is skyrimPlatform package?

### ISSUE THREAD

**Issue by gabrielmrts** [skyrim-multiplayer/skymp#1750]
hi guys, i'm trying to read the skymp5-client code, to understand more about how it works.. but i've found a problem, most of ts files import skyrimPlatform, but i can't find where is it.
Using linux.
Tried on Windows too.
I was thought that it's because i don't compiled the project..

**Comment by Pospelove** [comment]
hey, if you build whole project not just skymp5-client then it will be in build/dist. see https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-client/tsconfig.json#L3

however if you'll build skymp5-client separately it will fail
