### ISSUE TITLE
Modify `GetBaseActorValues` to take into account Actor Values of race and base NPC

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#184]

**Comment by SupAidmi** [comment]
@d0gge watch these links to make a task

https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format

https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/NPC

https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/RACE

**Comment by Pospelove** [comment]
Please unit test `GetBaseActorValues` with one of the races (ArgonianRace), with race=0. And baseId = 0x7 (it's id of NPC_)
