### ISSUE TITLE
[Question]: Edit Current NPC Dialouge [ Audio and .lip files ] Directly using SkyMP TypeScript

### ISSUE THREAD

**Issue by ftk789** [skyrim-multiplayer/skymp#1990]
### Description

I would like to edit the current interacted NPC dialouge aka the audio and the .lip files, Without using CreationKit ( Live editing )
Is that possible using SkyMP? And if not would it possible to be added as a feature?

**Comment by ftk789** [comment]
I've actually searched the whole internet for such a replica and Can't find any, Maybe I'm missing something? Any help here? I just want to dynamically and ( live hotswap ) the audio file and the lipsync of the current dialouge with a player and activate the dialouge, No need to be ordered or something, Just instantly hotswap and activate.

**Comment by Pospelove** [comment]
hey @ftk789 

Blurbs knows how to do that. you can ping hum in our [discord](https://discord.gg/k39uQ9Yudt) 
English section -> skyrim platform, and see if he'll help.

<img width="231" alt="image" src="https://github.com/skyrim-multiplayer/skymp/assets/37947786/9ef3caa8-9514-44d2-bb71-f2dd3a58e363">


Closing the issue for now :)
