### ISSUE TITLE
Improve SkyrimPlatform due to NexusMods feedback

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#208]
subtasks are WIP

- [x] #320
- [x] Support local page loading
- [x] Create HTML/CSS/JS integration demo (request from discord)
- [ ] https://github.com/skyrim-multiplayer/skymp/issues/270
- [x] #235
- [x] #323

**Comment by tauin** [comment]
probably also best to replace the thumbnail with the logo for the project, idk about anyone else, but i usually pay more attention to mods with a logo or text (i.e po3 mods)

**Comment by SlowsieNT** [comment]
Some useful features would be

**browser**
- `postMessage(aMessageStr)`
- `on`
  - `message`
    - rough example: `browser.on('message', () => browser.setFocused(false))`

**Game** (preferred):
  - Allow user to interact with `browser` visible components
    - Hotkey to redirect mouse/keyboard events to `browser` **if** mouse is in `browser` component

**Comment by Pospelove** [comment]
SP 2.1 is already released so the issue isn't up-to-date
