### ISSUE TITLE
Remove original NPC spawning

### ISSUE THREAD

**Issue by ZikkeyLS** [skyrim-multiplayer/skymp#224]
Remove NPC-related content due to instability

**Comment by Pospelove** [comment]
Please find the find the source file where the server spawns them and attach to your issue

**Comment by ZikkeyLS** [comment]
https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-server/cpp/server_guest_lib/WorldState.cpp#L346
hopefully
