### ISSUE TITLE
Unable to run npm run dev from install

### ISSUE THREAD

**Issue by generalconsensus** [skyrim-multiplayer/skymp#231]
1. Did npm install
2. Did npm run dev
```6:49:26 PM - Starting compilation in watch mode...

src/helloworld.ts(1,30): error TS2307: Cannot find module 'skyrimPlatform'.

6:49:26 PM - Found 1 error. Watching for file changes.

**Comment by Pospelove** [comment]
Hey. We've recently updated the plugin example. Didn't upload to NexusMods yet, but you better download zip of the repo https://github.com/skyrim-multiplayer/skymp/archive/refs/heads/main.zip
and use `skyrim-platform/tools/plugin-example` from the archive

Did you follow this? https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/tools/plugin-example/README.md

There is a step before `npm run dev`

**Comment by generalconsensus** [comment]
```
Steps:
1. 

PS I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mods\Skyrim Platform\Platform\plugin-example> npm install
npm WARN skyrimplatform-plugin-example@1.0.0 No repository field.

audited 29 packages in 0.462s
found 0 vulnerabilities

PS I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mods\Skyrim Platform\Platform\plugin-example> 

2. 

(Add config.js with location of Skyrim)

3.  

npm run dev

> skyrimplatform-plugin-example@1.0.0 dev I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mods\Skyrim Platform\Platform\plugin-example
> node ./tsc/before-first-compilation.js && tsc-watch --onSuccess "node ./tsc/on-success.js"

9:55:01 AM - Starting compilation in watch mode...

src/example.ts(1,47): error TS2307: Cannot find module 'skyrimPlatform'.
src/tests.ts(1,133): error TS2307: Cannot find module 'skyrimPlatform'.
src/tests.ts(3,22): error TS2307: Cannot find module 'skyrimPlatform'.
src/tests.ts(13,12): error TS7006: Parameter 'res' implicitly has an 'any' type.

9:55:02 AM - Found 4 errors. Watching for file changes.
```

Windows 10
npm version: 
```{
  'skyrimplatform-plugin-example': '1.0.0',
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}
```
node: v14.17.6
npm: 6.14.15

**Comment by Pospelove** [comment]
Does this link work for you? https://discord.gg/k39uQ9Yudt

**Comment by Pospelove** [comment]
@generalconsensus It seems you use MO2. Our instruction doesn't state clearly how to compile a test plugin without SP in the game folder. It would work if you place `Data/Platform/Modules/skyrimPlatform.ts` into your real Skyrim SE root. Please tell me if it works for you. Unfortunately, at this moment it's required to compile a test plugin. Mod users will not have to pollute the Data directory at all.

**Comment by generalconsensus** [comment]
I'll add a PR to fix that copy operation in the README.md. It works now!

**Comment by Pospelove** [comment]
Thanks! Let's keep this issue open

**Comment by generalconsensus** [comment]
#233 as requested so provided
