### ISSUE TITLE
Implement offline mode for server

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#236]
After discussing with @Pospelove we came up to adding some kind of offline mode (e.g. in such mode Minecraft server allows clients to connect with any username they choose).

This should work something like this: allow specifying user id somewhere in `gameData` in client config. When connecting to an offline mode server, it will use user id specified by client as-is, without any verification that user session is valid for master server.

(Probably this user id should be also sent by a logged-in client for consitency. Maybe we could migrate to verifying sessions based on it in the future.)

**Comment by Pospelove** [comment]
We need to add boolean offline mode option to `server-settings.txt`
example: https://github.com/skyrim-multiplayer/skymp/pull/49
offline mode should be disabled by default
Changes to `server-settings.txt` should be documented. Example: https://github.com/skyrim-multiplayer/skymp/pull/148

**How to change authorization behavior:**

skymp5-client sends to the server full `gameData` object from config to the server:
(regardless of data in this object)
```json5
{
  //...
  "gameData": {
    "profileId": 1123 // Let's allow our users in offline mode to just select any profileId in config
  }
}
```

There is an example of code that change authorization behavior: https://github.com/skyrim-multiplayer/skymp/pull/173/commits/a20e257dda4a793821b554029512c3e73a8cc91f
**Do not just copy, it's an example.** The example assigns fake profile ids that are equal to the userId.
Ping **nic11** if you aren't sure what userIds/profileIds are or debug source code.
