### ISSUE TITLE
Make server logs better

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#241]
Currently, server-side logs is a mess. There are some C++ logs, fancy formatted - info logs, some warnings on errors like taking too much from an inventory, they're actually pretty good. But there are also logs coming from JS code (whether Node.js part or skymp5-functions-lib, formerly gamemode), they're effectively just `console.log`, with no formatting like datetime or log level.

Example logs, C++ and JS ones:
<img width="557" alt="log example #1" src="https://user-images.githubusercontent.com/11034375/134750832-69385a02-170c-4424-9f86-5d418097ace4.png">
![log example #2](https://user-images.githubusercontent.com/11034375/134750948-ecc9e85c-5171-4acd-8594-bfcbde11dbb8.png)

Moreover, JS exceptions cause multiline log with stacktrace being printed. Multiple exceptions cause terminal being filled with stacktraces, leaving no space for other logs to be seen. Also, after some times, scrollback buffer ends, leading to

Probably a better solution for logging:
- [ ] Log more info, but only print some of the fields to the terminal. The detailed log should go to some file.
- [x] #812
- [ ] Log JS exceptions as one line (only exception type and message). Stacktrace should go to a separate file. Essentially, this is 1 and 2 combined.

<details>
<summary>Another ideas, that go beyond a minimal desired solution. In other words, it would be amazing if we could also do this, but absolutely not required</summary>

4. Maybe introduce some kind of logging context. This will help debugging specific actions caused by an incoming packet or actions caused by a specific player.
5. Another possibility is to be able to specify log level depending on some per-cell or per-player config. E.g. if we know that some location has some bugged behavior, we could raise log level from INFO to DEBUG there.
</details>

**Comment by Pospelove** [comment]
Assigning myself to get back to this issue later and split it into tasks.

**Comment by Pospelove** [comment]
I did some things so let's think it's fixed in main branch
