### ISSUE TITLE
Spell.cast(target, caster)

### ISSUE THREAD

**Issue by hjk30** [skyrim-multiplayer/skymp#244]
Spell.cast (target, caster) just doesn't work regardless of target and caster, and the spell itself

**Comment by numen13** [comment]
Crashes with following error even when a valid ObjectReference is provided
ERROR: Type mismatch for argument 1. stack:<empty stack>

**Comment by Pospelove** [comment]
@numen13 Wow! Could you please provide a full code snippet by the way? And log screenshot. Thanks in advance!

**Comment by numen13** [comment]
It is just a little test script to get in touch with Skyrim Platform:
The same occurs if spell.cast is directly called with the player Actor
`
  on("unequip", async (event) => {
    try {
      // const form = Game.getForm(0x11001829)
      const form = Game.getForm(0x10000D65)
      if(form){
        const spell = Spell.from(form)
        if(spell){
          const player = Game.getPlayer()
          if(player){
            spell.setNthEffectMagnitude(0, 20)
            printConsole('form name:' + form.getName())
            printConsole('form form id:' + form.getFormID())
            printConsole('spell name:' + spell.getName())
            printConsole('spell form id:' + spell.getFormID())
            const objRef = ObjectReference.from(player)
            if(objRef){
              printConsole('objRef name:' + objRef.getName())
              printConsole('objRef form id:' + objRef.getFormID())
              spell.cast(objRef, null)
            }
          }
        }
      }
    } catch (error) {
      printConsole('' + error)
    }
  });
`
[Crash_2021_11_13_1-10-48.txt](https://github.com/skyrim-multiplayer/skymp/files/7531128/Crash_2021_11_13_1-10-48.txt)

**Comment by Pospelove** [comment]
probably fixed in the coming 2.6
