### ISSUE TITLE
Install node_modules in launch_server.bat if it does not exist

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#255]
Since packing node_modules in dist (#179) was not successful, we can just call `npm install` from server laucher batch file.

More specifically, copy `package.json` and `package-lock.json` to `dist/server` and replace setting `NODE_PATH` with checking if `node_modules` exist

**Comment by Pospelove** [comment]
outdated. node_modules now not required soo fixed in main branch
