### ISSUE TITLE
OnItemAdded

### ISSUE THREAD

**Issue by FredericoGauz** [skyrim-multiplayer/skymp#269]
Hi, is there a way to get the "OnItemAdded" event or some work around for it?

Thanks in advance

**Comment by Pospelove** [comment]
Hi, there is `containerChanged` event that covers your needs:

```ts
import * as sp from "skyrimPlatform";
sp.on("containerChanged", (e) => ...);
```

**Comment by FredericoGauz** [comment]
Hi, thanks! I tried to use it but I couldn't find how to get the item that was added. Only the container where the item was taken and where was put in.

Would there be a way to find it out?

**Comment by FredericoGauz** [comment]
Also (related to this question), would there be a way to subscribe to a certain object events. (like with registerForUpdates, registerForCrosshairRef, etc?

Thanks

**Comment by Pospelove** [comment]
> Hi, thanks! I tried to use it but I couldn't find how to get the item that was added. Only the container where the item was taken and where was put in.
> 
> Would there be a way to find it out?

`e.baseObj` to access the item that was added (base type).
`e.numItems` to access the number of items transferred.

**Comment by Pospelove** [comment]
> Also (related to this question), would there be a way to subscribe to a certain object events. (like with registerForUpdates, registerForCrosshairRef, etc?
> 
> I think I can manage to create those missing events and object events if needed.
> 
> I would also want to investigate the possibility of adding new hooks. Please let me know how I can help and if someone can give me some instructions on how do one of each of these (in order for me to work on the rest of them...)
> 
> At the moment I am not using any multiplayer features, I would be very happy being able to make the platform work with these new features.
> 
> Thanks again

registerForUpdates, registerForCrosshairRef, and others are not usable, unfortunately. but they are not required for SP. we can do the same with SP instruments.

about hooks: that's not super-hard. however, we do not have a ready tutorial.

**Comment by Pospelove** [comment]
btw better to discuss these things in discord :)

**Comment by Pospelove** [comment]
Closing for now. Feel free to open a new issue/reopen/ask questions in Discord

**Comment by Pospelove** [comment]
@FredericoGauz 
![image](https://user-images.githubusercontent.com/37947786/136233756-9c2aaac7-fb61-4ec4-b086-de57b8e02303.png)
react with a flag to unlock channels

**Comment by FredericoGauz** [comment]
Ah ok, thanks. Sorry for not thinking about that!
