### ISSUE TITLE
[Bug]: Flying npc

### ISSUE THREAD

**Issue by Banan1447** [skyrim-multiplayer/skymp#303]
### Severity

Minor. A minor defect that doesn''t violate the application''s functionality when tested, but influences the expected result. A design error wobe one example. A bug that doesn't affect the functionality or operation of the app but can be detected visually, for example, a typo in the text.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

[](url
![ScreenShot0](https://user-images.githubusercontent.com/37272362/136668666-8f0f4204-72c7-4800-b140-6fb7a1c3d97c.png)
)

When location was loaded npc's get flying on random height but physicaly hitting me like they was on the ground, another player witch connect to server dont see it and for he all was ok npc was staying on the ground

### OS

Windows

### OS version

11

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

f94ca3d7ee01e716e42f1e9364d6999b7927d887

### server commit''s hash

f94ca3d7ee01e716e42f1e9364d6999b7927d887

### Videocard model

AMD RX 590

### Steps to reproduce

1.get in interior(any other location)
2.get out of location 
3.npc get flying a random pos(sometimes on big speed)
4.if you go in,than get back to interior it helps but not all time
5.when its happens game may crash 
6.it work at 40% chance  

### Expected result

When you get inside building and than went outside
NPC should be on ground.

### Actual result

When you get inside building and than went outside
NPC flying randomly position

**Comment by kkEngine** [comment]
This bug also can happened when reloading skymp5-client
