### ISSUE TITLE
CSS Animations quickly taking up all memory available

### ISSUE THREAD

**Issue by FredericoGauz** [skyrim-multiplayer/skymp#314]
When running css animations in Skyrim Platform the amount of memory the application uses quickly escalates to an immensurable size taking over all computer memory.

Although this by itself is not a very important issue, I think that it becomes important when thinking about how the application handles the state updates of the UI and garbage collection. I have been noticing quite a few memory hogs after using the internal browser for a while and thought it worth mentioning.

Again, I will be happy to help fixing it.

**Comment by FredericoGauz** [comment]
Here is a quick example:
`
@media (prefers-reduced-motion: no-preference) {
    .App-logo {
        animation: App-logo-spin infinite 20s linear;
    }
}`

**Comment by Pospelove** [comment]
feel free to reopen if it's still an issue. closing for now
