### ISSUE TITLE
[Bug]: Created players are immortal when spawn(create character)

### ISSUE THREAD

**Issue by Banan1447** [skyrim-multiplayer/skymp#339]
### Severity

Minor. A minor defect that doesn''t violate the application''s functionality when tested, but influences the expected result. A design error wobe one example. A bug that doesn't affect the functionality or operation of the app but can be detected visually, for example, a typo in the text.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

when im create 2 characters whey cant damage each other until they both gonna run.

### OS

Windows

### OS version

11

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

1b2483b4c5066df92fd67a2662cce8f584be8938

### server commit''s hash

1b2483b4c5066df92fd67a2662cce8f584be8938

### Videocard model

AMD RX590

### Steps to reproduce

1.)User1 create player and its immortal (can give damage|can't take)
2.)User2 create player and its immortal (can give damage|can't take)
3.) User1 gonna run he feel all damage what he taken from creation player (can give&take)
4.)same to User2 if he run u can damage him (can give&take)

### Expected result

Dont need to run to feel any damage

### Actual result

you immortal until you press "alt" and run

**Comment by kkEngine** [comment]
After the tests we have the following situation:
1. Fall damage does not work at all
2. There is no damage messages from server If the player has 100% health (only restore message if player were hit). If player jumps or sprint (using "alt") the client starts to receive damage messages. While the client receives damage messages, player can be hit with properly health display.
