### ISSUE TITLE
Implement initialValue for inputs

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#359]
initialValue (true / false for checkbox, string for text inputs). if initialValue changes over time and whether it ceases to correspond to the current value of the input, checkbox, etc., then we do nothing. that's why it is initial.

Depends on #360

**Comment by vladdenisov** [comment]
Seems like it's already implemented.
`{ type: "inputText", text: "hello" }` will set initialValue to `hello`.

Maybe we need to rename it to initialValue to use it like `{ type: "inputText", initialValue: "hello" }`?

**Comment by Pospelove** [comment]
I'll take a look
