### ISSUE TITLE
Use UpdateProperty packet instead of ChangeValues

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#410]

**Comment by kkEngine** [comment]
Is it relevant?

**Comment by Pospelove** [comment]
@kkEngine Yes, we want to standardize how the server updates the properties of players and always use the `UpdateProperty` packet type instead of creating new packet types again and again. Your expertise on this is welcome! Feel free to leave your thoughts.

**Comment by Pospelove** [comment]
Now seems irrelevant
