### ISSUE TITLE
Implement a concrete struct for adding overlay game texts

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#430]
Pass the `ForEachTextToDraw` function into the `DX11RenderHandler` from `main.cpp`, which will provide access to the array of TextToDraw (x, y, size, string, color with alpha) structures and render them.

**Comment by Pospelove** [comment]
Previous proposal by @nic11 

> Something like this:
> 
> ```c++
> // Some object which should be rendered as an overlay.
> // E.g. player name, status bar, CEF view, etc.
> class IOverlayObject
> {
> public:
>   virtual ~IOverlayObject() = default;
> 
>   IOverlayObjectRenderer StartRender(/* some params */) const = 0;
> };
> 
> // Holds parameters which decide if object should be rendered and where.
> // Parameters should include:
> // * Screen size
> // * Object in-world position (if any)
> // * Camera position and angle
> // * ... maybe something else
> class IOverlayObjectRenderer
> {
> public:
>   virtual ~IOverlayObjectRenderer() = default;
> 
>   bool IsVisible() const = 0;
>   Vector2 GetPosition() const = 0;
>   Vector2 GetSize() const = 0;
>   void Render(/* some DirectX object */) const = 0;
> };
> ```
> 
> Naming or API is not final and may change after discussion with @Pospelove and with an assignee for this task.
