### ISSUE TITLE
Support RelWithDebInfo builds

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#437]
Currently, it's failing because there's no RelWithDebInfo build for CEF. We can use regular Release builds for CEF.

`LINK : fatal error LNK1104: cannot open file '..\..\vcpkg_installed\x64-windows-sp\share\cef-prebuilt\RelWithDebInfo\cef_sandbox.lib' [D:\a\skymp\skymp\build\skyrim-platform\_platform_se\SkyrimPlatformCEF.vcxproj]`

**Comment by Pospelove** [comment]
> btw our release build contains debug info by defaultc
so closing for now. feel free to reopen if needed
