### ISSUE TITLE
[Bug]: Movement has a noticeable delay.

### ISSUE THREAD

**Issue by SupAidmi** [skyrim-multiplayer/skymp#444]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Every action in the game has a noticeable delay. On average, from 250 to 600 ms. When player 1 performs any action (movement, attack, etc.) for player 2, this action is displayed with a delay. All this makes a non-targeted combat system meaningless, since it becomes very difficult to quickly block attacks, dodge and hit other players with such a long delay. Which in turn reduces the tactics of combat to a banal mouse clicking.

### OS

Windows

### OS version

10

### Skyrim version

1.5,97,08

### SKSE version

2.0.20

### client commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### server commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### Videocard model

RX 470

### Steps to reproduce

See video

https://drive.google.com/file/d/11Giy4JE7t4nNj0HNbMZxvcQZVGnmvrp9/view?usp=sharing

### Expected result

The delay is minimal.

### Actual result

Delay in the range from 250 to 600 ms.

**Comment by Pospelove** [comment]
fixed
