### ISSUE TITLE
[Bug]: Your footsteps are faster than footsteps of other players

### ISSUE THREAD

**Issue by SupAidmi** [skyrim-multiplayer/skymp#445]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

When player 1 plays any animation for other players, this animation plays slower, by about 20%.
See the attached video.

https://drive.google.com/file/d/1TXazkaBgzTPXzsHf_kqfXUSNR6e0cgh2/view?usp=sharing

### OS

Windows

### OS version

10

### Skyrim version

1.5,97,08

### SKSE version

2.0.20

### client commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### server commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### Videocard model

RX 470

### Steps to reproduce

1. Enable displaying player clone in client setting
2. Walk 10 steps forward and count number of steps for player and his clone.

### Expected result

The number of steps for the player and his clone should be the same

### Actual result

The number of steps for the player and his clone are not the same

**Comment by Pospelove** [comment]
mentioned in roadmap. closing
