### ISSUE TITLE
Set hard order of death packets

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#467]
https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-server/cpp/server_guest_lib/MpActor.cpp#L329

We keep operations order:
```c++
TeleportUser(position);
SetAndSendIsDeadPropery(false);
```
But send with `RELIABLE_ORDERED` mode instead of `RELIABLE`. Networking currently supports true/false values (`RELIABLE`/`UNRELIABLE`). We need to add `RELIABLE_ORDERED` support and use it to **guarantee packets order.**

**Comment by kkEngine** [comment]
Need "Before" option for the skymp client
1. Teleport
2. isDead = false

**Comment by Pospelove** [comment]
Fixed issue description

**Comment by Pospelove** [comment]
Closing in prior to #483
