### ISSUE TITLE
Can not load local static html

### ISSUE THREAD

**Issue by TheFBplus** [skyrim-multiplayer/skymp#489]
I put a simple index.html in the folder "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Platform\UI" and use `browser.loadUrl("file:///Data/Platform/UI/index.html");`to load the file,but nothing happend.
works fine with `browser.loadUrl("https://google.com");` or  `browser.loadUrl("http://localhost:xxxx"); `Is there something wrong?

**Comment by Pospelove** [comment]
It doesn't work for SP 2.0 which is uploaded to Nexus currently. SP 2.1 is going to be uploaded soon, the fix of your problem is included
