### ISSUE TITLE
Iterate over packages in update and not tick, so as not to waste 17ms locally when applying sync

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#511]
Not sure if it's about SP or client or both. Need @kkEngine expertise

**Comment by Pospelove** [comment]
@kkEngine any progress on this? is this issue valid?

**Comment by kkEngine** [comment]
WIP right now :)

**Comment by kkEngine** [comment]
If you change this line (https://github.com/skyrim-multiplayer/skymp/blob/85dbed61c03e82f68cd2a7628d3510d15b6e8e51/skymp5-client/src/networking.ts#L19) to "update" the game won't load. It seems logical that we are not handling network messages in the game context.
I guess i am not sure that i understand this issue :)

**Comment by Pospelove** [comment]
@kkEngine We can handle some messages in "update" if it's reasonable. Some in "tick". There is no "tick" in the main menu.

**Comment by kkEngine** [comment]
> We can handle some messages in "update" if it's reasonable
I think it's not worth it

> There is no "tick" in the main menu.
о_О "tick" works in the main menu. Why not?

**Comment by Pospelove** [comment]
@kkEngine sorry. tick works, update doesn't work

**Comment by Pospelove** [comment]
@kkEngine let's pause this task for now.

**Comment by Pospelove** [comment]
stale
