### ISSUE TITLE
Implement login/register

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#514]
When a person is half connected, spawn him locally in the lobby, freeze him and show the registration/authorization menu. Connect to the server only when it is authorized. Implement with Server Master (skymp.io/api)

**Comment by Pospelove** [comment]
See https://github.com/skyrim-multiplayer/skymp/issues/368

**Comment by kkEngine** [comment]
`
window.skyrimPlatform.sendMessage("myEvent", window.localStorage.getItem("key"));
`
causes error "Failed to read the 'localStorage' property from 'Window': Access is denied for this document".

**Comment by Pospelove** [comment]
@kkEngine 
Try `writePlugin`/`getPluginSourceCode` as a hacky workaround. But this unfortunately forces hot-reload.

**Comment by kkEngine** [comment]
How to open github and patreon ref in user's default browser?

**Comment by Pospelove** [comment]
@kkEngine https://github.com/skyrim-multiplayer/skymp/issues/638
