### ISSUE TITLE
Add awesome Skyrim Platform list

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#539]
TODO: List SP-powered mods in issue description

Easy Containers - https://www.nexusmods.com/skyrimspecialedition/mods/56923
Auto unequip ammo SP - https://www.nexusmods.com/skyrimspecialedition/mods/57221
Read Tome Forget Spell - https://www.nexusmods.com/enderalspecialedition/mods/301

**Comment by CarlosLeyvaAyala** [comment]
We put links to our mods here?

**Comment by Pospelove** [comment]
@CarlosLeyvaAyala Yes, let's post links here and pull request the issue link to the docs

**Comment by CarlosLeyvaAyala** [comment]
These are mine:
- Easy Containers - https://www.nexusmods.com/skyrimspecialedition/mods/56923
- Auto unequip ammo SP - https://www.nexusmods.com/skyrimspecialedition/mods/57221

May I tag @everyone on Discord so everyone knows about this?

**Comment by Pospelove** [comment]
@CarlosLeyvaAyala yes 🤣

**Comment by Y3sMan** [comment]
Read Tome Forget Spell - https://www.nexusmods.com/enderalspecialedition/mods/301

**Comment by Pospelove** [comment]
It's outdated and will be outdated forever. Hard to maintain the list. Closing for now
