### ISSUE TITLE
Actor is missing getActorBase and other functions written in Papyrus

### ISSUE THREAD

**Issue by mrowrpurr** [skyrim-multiplayer/skymp#543]
The `Actor` script seems to have every function that the Papyrus `Actor` has, except: `getActorBase()`. It's missing!

**Expected:**

`Actor.getActorBase()` to be available

**Actual:**

It's not!

https://www.creationkit.com/index.php?title=GetActorBase_-_Actor

**Comment by Pospelove** [comment]
> This function is actually GetBaseObject() as Actorbase, and is faster than this function.

I've figured out why is it missing, it's non-native. We should add it or document to always use `ActorBase.from(actor.getBaseObject())`

**Comment by Pospelove** [comment]
Note for me: We are able to decompile these functions with our PapyrusVM (Reader)
Or even execute them. Just every time we need other native -> go to real natives

**Comment by Pospelove** [comment]
Or we should just try `sp as any` hack first

**Comment by Pospelove** [comment]
I think it shouldn't be fixed on SP level
