### ISSUE TITLE
Skyrim Platform: Add a new event hook to replace SPID hack

### ISSUE THREAD

**Issue by CarlosLeyvaAyala** [skyrim-multiplayer/skymp#549]
# Motivation
We have an `objectLoaded` event that is quite odd on its way of working (I suppose it just exposes an undocumented SKSE/CommonLib event no one really knows about).
It only works for some objects, so it's not reliable for, say... running code on `Actors` as soon as they spawn.

Right now, the only way to reliable do that is to use SPID and [this technique](https://github.com/skyrim-multiplayer/skymp/blob/main/docs/skyrim_platform/cookbook.md#getting-rid-of-cloaks).

# Solution
I thought I was at least somewhat capable of trying to tackle this issue (boy... how was I wrong!) by studying the SPID source code and adding the equivalent hook on FridaHooks.cpp or something.

This is as far as I could get:
https://github.com/powerof3/Spell-Perk-Item-Distributor/blob/8f384141f308b5b02c0023b4f2927270dfb6f4d9/SPID/src/main.cpp#L30

I now this line seems to somehow be related to applying spells, but I have no way of knowing which event triggers this code.

So, any help is highly appreciated.

**Comment by Pospelove** [comment]
no activitiy. closing
