### ISSUE TITLE
Idea: Store `writeLogs` and `settings` outside of Platform\Plugins

### ISSUE THREAD

**Issue by mrowrpurr** [skyrim-multiplayer/skymp#553]
**Request:** provide an option to store `writeLogs` and `settings` in folder other than `Platform\Plugins` (_or change the default folder_)

**Why?** using this folder breaks hot reloading for MO2 users

**Related:**
- https://github.com/skyrim-multiplayer/skymp/issues/552

---

### Scenario

As a Skyrim Platform developer
I can use Mod Organizer 2
And I can write logs (or) use settings
And I get hot reloading

### Steps

1. Create a new plugin
2. Use either `writeLogs("my-plugin", "hello, world!")` or `settings["plugin-name"]["my-option"]`
3. Run the game using MO2
4. Observe, logs (_or settings_) were written to `Overwrite\Platform\Plugins\*`
5. Recompile your plugin and observe hot reloading work
6. Exit the game
7. Relaunch the game using MO2 (_now that there are files in `Overwrite\Platform\Plugins\`_)

### Expected

8. Recompile your plugin and **observe hot reloading work**

### Actual

8. Recompile your plugin and **observe hot reloading _NOT_ work**

### Why?

If a `Platform\Plugins` folder exists in the MO2 Overwrite folder, then it will be mounted via MO2's `vfs`

Anything mounted with `vfs` cannot be updated at runtime

### Impact

All SP developers using MO2 who want to use either `writeLogs` or `settings`

**Comment by mrowrpurr** [comment]
**UPDATE**: Looks like `writeLogs` already supports this, this is done. Just `writeLogs('../diff/folder', 'hi')`

**Comment by Pospelove** [comment]
@mrowrpurr Can we close that issue since we have `Plugins` /`PluginsDev` and `Data/Platform/Logs`?

**Comment by mrowrpurr** [comment]
@Pospelove 💯

**Comment by Pospelove** [comment]
@mrowrpurr Thanks. Looking forward to it.

**Comment by mrowrpurr** [comment]
Related important note from a user reported on their mod's Nexus page:
> There is a Skyrim Platform bug where if one settings file is edited, every single plugin is reloaded.
- https://www.nexusmods.com/skyrimspecialedition/mods/61556

Logs were moved into a separate folder but settings remain next to the plugin .js which cause an auto-reload on changes to settings files.

2 unrelated issues both stem from the location of the settings files

**Comment by duffbeeeer** [comment]
The new SPCM seems really promising for having an MCM for SP but this issue seems to break its hot reloading feature and makes it unusable for anyone using mo2.

**Comment by Pospelove** [comment]
@duffbeeeer @mrowrpurr So we want to reload only a plugin/settings file that has been changed?

**Comment by duffbeeeer** [comment]
I'm not sure if the new values would be getting used by the plugin without the need to reload plugin itself? If yes, then a settings file for hot reload is good enough.

**Comment by Pospelove** [comment]
> Request: provide an option to store writeLogs and settings in folder other than Platform\Plugins (or change the default folder)

seems that the original request has been implemented. closing for now.
feel free to ping me if I didn't get right!

**Comment by Pospelove** [comment]
@duffbeeeer  @mrowrpurr  See https://github.com/skyrim-multiplayer/skymp/issues/746
