### ISSUE TITLE
Add a way to unsubscribe from `on`/`once`

### ISSUE THREAD

**Issue by edho08** [skyrim-multiplayer/skymp#559]
### Motivation
The way SP interact with skyrim is through events. The 'new-event' are a way to subscribe to an event using `once` or `on`. The caveat is, once one subscribe to an event using `on`, one cannot unsubscribe unless 'hot-reload' happened or the game close. 
### Feature Requested
Some way to unsubscribe from the 'new-event' when subscribing using `on`. The implementation details are left up to contributors. One example of implementation is asking for a boolean return value for a function that subscribe to an event. when the function return true, it will still subscribe to an event while returning false means unsubscribe for later events. But this is intrusive to already established mod. Another possible implementation would be to return an object upon calling `on` that need to be interacted with to unsubscribe from an event. For example, one would subscribe using `let handler = on(arg1, arg2)` then later would do `handler.done()` to unsubscribe.
### Current Solution
There is a way currently to unsubscribe from an event when subscribing to 'new-event'. The way to do this is to ditch `on` completely but rather using `once` after each event call. then chose to return true to continue subscribing or return false to unsubscribe. This however add an overhead (but not much) and rely on the fact that each events are handled sequentially, which might not be true in the future. Consider the function below.
``` 
public static registerForRepeatEvent(type:any, func : (event:any) => boolean):void{
	once(type, (e:any)=>{
		if (func(e))
			registerForRepeatEvent(type, func);
	});
}
```

**Comment by Pospelove** [comment]
fixed in main thanks
