### ISSUE TITLE
How to uninstall mods downloaded by launcher?

### ISSUE THREAD

**Issue by Tiagox42** [skyrim-multiplayer/skymp#57]
How to uninstall mods downloaded by launcher? Do you have any log files that were added?

**Comment by Pospelove** [comment]
> How to uninstall mods downloaded by launcher? Do you have any log files that were added?

We have just deprecated the launcher. 
1) Remove `tmp` and `Mods` from your Skyrim SE dir
2) Remove everything from the `Data` folder, except heavy .esm/.bsa files. As far as I know, the launcher never modifies them.
3) Verify integrity of game files in Steam.

I'm disabling the download link right now to prevent confusing anyone. I believe in the future we can implement a new launcher that wouldn't pollute the game directory. Please let us know if the instruction above isn't helpful.

**Comment by Pospelove** [comment]
Closing for now. Feel free to reopen if needed.
