### ISSUE TITLE
Request: add on(eventName: string)  and once(eventName: string) overloads

### ISSUE THREAD

**Issue by mrowrpurr** [skyrim-multiplayer/skymp#579]
### Story

As a Skyrim Platform developer  
I should be able to call `on` and `once` by providing a string parameter for `eventName`
e.g. `on('container' + 'Changed')`
And it should work
So that I can use non-literal strings for eventNames
And so that I I can make my own interface for these functions for unit testing
e.g. `interface OnEvent { (eventName: string, callback: (event => any) => void) }`

### Steps to Reproduce

```ts
on('container' + 'Changed', event => {})
on('update', event => {})
```

### Expected Behavior

This works

### Actual Behavior

```
Plugin.ts(9,4): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string' is not assignable to parameter of type '"consoleMessage"'
```

### Solution

Add these 2 overloads to `skyrimPlatform.ts`

```ts
export declare function on(eventName: string, callback: (event: any) => void): void
export declare function once(eventName: string, callback: (event: any) => void): void
```

I would send a pull request but I believe `skyrimPlatform.ts` might be generated:?

Note: assuming there is _one_ implementation of the `on` and `once` functions somewhere, these overloads should work just fine. The implementation probably already has this exact call signature.

### Why?

In my Unit Tests I need to be able to mock the `on()` and `once()` functions.

More specifically, I'd actually like my implementation to be able to use interfaces for these functions.

The ideal way of doing this:

```ts
interface IOn { (eventName: string, callback: (event: any) => void) => void: void }
interface IOnce { (eventName: string, callback: (event: any) => void) => void: void }

class MyImplementation {
  on: IOn
  once: IOnce

  constructor(on, once) {
    this.on = on
    this.once = once
  }

  public something() {
    this.once('update', () => {
      // ...
    })
  }
}
```

Then in my tests I provide fake implementations for doing mock things on these function calls and asserting the function calls OK.

And I have a generator function somewhere which gives you the real thing for the real application:

```ts
import { on, once } from "skyrimPlatform"

export function getMyThing() => {
  return new MyImplementation (on, once)
}
```

This has been working super well for me, but I needed to add these 2 lines to `skyrimPlatform.ts` to make it work:

```ts
export declare function on(eventName: string, callback: (event: any) => void): void
export declare function once(eventName: string, callback: (event: any) => void): void
```

Adding those somehow to the generation template or directly to `skyrimPlatform.ts` should 'just work'

**Comment by mrowrpurr** [comment]
Note: this is doable today if I implement interfaces for _every variable_ of `on` and _every variable` of `once` -- or just the variants I'm actually calling.

https://javascript.plainenglish.io/mocking-ts-method-overloads-with-jest-e9c3d3f1ce0c

I'll update my tests to use interfaces like:
```ts
interface OnContainerChanged {
  eventName: 'containerChanged', callback: (event: ContainerChangedEvent) => void: void
}
```
... and that should let me write my application _without this change_. It sure would be convenient tho :)

**Comment by Pospelove** [comment]
@mrowrpurr Hey! Thanks for posting a detailed request.

It's expected that we can not pass raw strings as event names. This limitation protects us from typos.

However, I think we still can fix our typings. Maybe it'll help with your problem.
I'm pretty sure TS can do smth like that:
```ts
export declare function once<T extends 'equip' | 'magicEffectApply'>(eventName: T, callback: (event: EventContents<T>) => void): void;
```

Asking [here](https://discord.gg/ybxFnNuMHS) may help with fixing typings. I always use this Discord server when I do not understand something in TS.

The base file for codegen is here. Feel free to contribute to this file!
https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt

**Comment by Pospelove** [comment]
Workaround (as always)
```ts
import * as sp from "skyrimPlatform";
type YourOnType = ...
const on = (sp as Record<string, YourOnType>).on;
```

@mrowrpurr

**Comment by mrowrpurr** [comment]
Let's close this again and let folks figure out their own ways of mocking `on` and `once`

If anyone searches for and finds this, here's what I ended up doing. Note: it means you have to configure each on/once callback separately, but I think that's actually okay:

#### Class which uses `on` - `MyPlugin.ts`
```ts
import { ContainerChangedEvent } from 'skyrimPlatform'

export interface OnContainerChange {
    (callback: (event: ContainerChangedEvent) => void): void
}

export default class MyPlugin {
    constructor(onContainerChange: OnContainerChange) { // <--- will allow for dependency injection
        onContainerChange(event => {
            const itemName = event.baseObj.getName()}
            // Do something!
        })
    }
}
```

#### Real implementation - `index.ts`
```ts
import { on } from 'skyrimPlatform'
import MyPlugin from './MyPlugin'

new MyPlugin(onContainerChange => {
    on('containerChanged', onContainerChange) // <--- inject a real implementation
})
```

#### Test Implementation - `MyPlugin.test.ts`
```ts
import { ContainerChangedEvent } from 'skyrimPlatform'
import MyPlugin from './MyPlugin'

describe('MyPlugin', () => {
    it('does something when container is changed', () => {
        const containerCallbacks = new Array<callback: (event: ContainerChangedEvent) => void>()
        const plugin = new MyPlugin(onContainerChange => {
            containerCallbacks.push(onContainerChange) // <--- inject a testimplementation
        })
        // Now we can trigger a 'container change' whenever we want
        containerCallbacks.forEach(callback => callback({
            oldContainer: x,
            newContainer: x,
            baseObj: x,
            numItems: x,
            uniqueID: x,
            reference: x
        }))
    })
})
```

Looks like a lot, but really it works out super duper well for me. Let's close this!
