### ISSUE TITLE
Fix that Windows CI can not build Yarn projects 

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#600]
Example build log
https://github.com/skyrim-multiplayer/skymp/runs/4411669556?check_suite_focus=true

**Comment by nic11** [comment]
Looks like this is almost the same issue (the only difference is that we've switched to yarn since then): #55

**Comment by nic11** [comment]
@Pospelove BTW I don't see fails before Nov 29. Maybe it's related? Couldn't confirm, but... One of the changes there was updating Node 14 to Node 16.

I didn't see successful builds with Nov 29 image here:
<img width="728" alt="Screenshot_20211205_215557" src="https://user-images.githubusercontent.com/11034375/144759722-b88e4056-948d-4683-bdb3-51fc3d6dc327.png">

See
1. https://github.com/actions/virtual-environments/blob/win19/20211229.2/images/win/Windows2019-Readme.md
2. https://github.com/actions/virtual-environments/releases/tag/win19%2F20211229.2
