### ISSUE TITLE
Font license issue

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#624]
https://github.com/skyrim-multiplayer/skymp/pull/592 adds font to the repo
We need to rename the font to its real name
Then we need to mention this font in our LICENSE file

**Comment by Pospelove** [comment]
@SupAidmi Please answer me on this issue. What fonts do we use and what licenses do they have?

**Comment by SupAidmi** [comment]
Black Horse Courier - modifaed Bankir-Retro by A. L. Gopfmann 2006, free

Tavern - modifaed Typey McTypeface: ver 1.3 by Paul J. Miller 2016 & Dieter Steffmann 1995, Sil Open Font License (OFL)

Tavern Light - modifaed NK124 by Cirilicna Slova Dodao Nikola Kovanovic free for all uses except commercial
