### ISSUE TITLE
Add magic effects system (perks, enchantments and other)

### ISSUE THREAD

**Issue by Dinakrab** [skyrim-multiplayer/skymp#632]
If player equips armor with enchantment magic effect should be add to player's modifiers.
For example. If you equipped armor with damage resist effect then it be add to magic damage resist actor value instead of notice this effect in damage formula and etc.

This values should consist of multiplicative and additive parts. We must store resulting value and list of all player's effects

**Comment by Pospelove** [comment]
no activitiy. closing for now
added to roadmap
