### ISSUE TITLE
Fix Papyrus states support

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#644]
Originally posted by Potato150: https://github.com/skyrim-multiplayer/skymp/issues/129

**Comment by Pospelove** [comment]
We need **minimal** example script that reproduces the problem

**Comment by 4Friends-pospelov** [comment]
issue author said that issue is invalid. discussed privately in discord

**Comment by Pospelove** [comment]
From discord: 
> The states work, I made them crooked like
Seems invalid. closing
