### ISSUE TITLE
Fix threading issue: game functions must be called in the game thread, not chakra thread

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#653]
[SkyrimPlatform](https://www.nexusmods.com/skyrimspecialedition/mods/54909) uses [JsEngine](https://github.com/skyrim-multiplayer/skymp/blob/main/chakra-wrapper/JsEngine.h) to register native functions in JavaScript runtime.

These native functions expose the functionality of the original game scripting system (Papyrus).
So you can call Papyrus functions from JavaScript/TypeScript.

For example, `skyrimPlatform.Game.getPlayer()`
(functions in the Game script are listed here https://www.creationkit.com/index.php?title=Game_Script)

**JsEngine doesn't work in the game thread. So we allocate our own thread to process JsEngine.**
https://github.com/skyrim-multiplayer/skymp/blob/f77bdf3f572e0a24d3717af5b7d4e0d7b2e3b9b3/skyrim-platform/src/platform_se/skyrim_platform/main.cpp#L104

But when the execution flow goes to the game functions, some of them expect the game thread. **We already sync threads but it doesn't work. It seems that game functions have thread_local under the hood or something**

here is the code we want to be executed in game thread, not js thread
https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/skyrim_platform/CallNative.cpp#L498

***

Proposed solution:

We should somehow do `f->Call` in the game thread. This thread is inside `PushAndWait` and it just waits for js thread that does work.

So I think we can make game thread to wait for new `f->Call` jobs, not full `PushAndWait` finish. And execute these `f->Call` jobs in game thread.

We need to do it as cheaply as possible. Otherwise, long synchronization times will affect all function calls in SkyrimPlatform.

***

**How to test**

This section is WIP. I'm gonna write test instructions here. For now you can ask me or kkEngine in Discord.

***

Fixing this will help with a bunch of issues:

- [ ] #563
- [ ] #245
- [ ] #244
- [ ] #706
- [ ] #786 

And other undocumented problematic functions.
And also would allow us to remove hacks like our own `sendAnimationEvent` reimplementation.

**Comment by Pospelove** [comment]
@nic11 Maybe you have thoughts on this.

**Comment by Wedmer** [comment]
Possible solution: 
Use something like (boost::)asio::io_context
Example flow for io_context:
js "calls" desired function via wrapper  -> wrapper creates lock via  condition_variable and posts a new job for io_context  in game_thread with desired function and shared object to store result -> in game thread function executes, fills shared object and notifies  condition_variable to unlock -> wrapper returns (result).

There're more variants for io_context. Also we can use something like boost::coroutine2 or even boost::fiber

**Comment by Pospelove** [comment]
@Wedmer We probably can solve the problem by condition variables only, without asio.
Game thread will wait for var1, js thread - for var2. Am I right?
