### ISSUE TITLE
Bug: Console shows [Exception] DirectoryMonitor if Plugins and/or PluginsDev are not present

### ISSUE THREAD

**Issue by mrowrpurr** [skyrim-multiplayer/skymp#666]
If you do not have a Data\Platform\Plugins folder or Data\Platform\PluginsDev folder, you get erros in the Skyrim console which are visible at game launch

![Screenshot (257)](https://user-images.githubusercontent.com/87039589/147107380-a14d95eb-6206-40ea-bb25-1222a1a99a8a.png)

This could be confusing for users. And I generally think it's not a useful error. I don't personally want a PluginsDev folder _unless_ I am actively developing plugins

**Comment by Pospelove** [comment]
@mrowrpurr What is expected behavior then? error for `Plugins` and no error for `PluginsDev`?

**Comment by mrowrpurr** [comment]
I wouldn't expect anything to appear in the console. It's totally fine to
run Skyrim Platform without these folders. And it's not really a
user-related error at all.

**Comment by mrowrpurr** [comment]
If you want something it appear, maybe just "No Plugins detected" when no
Plugins or PluginsDev folders

**Comment by Pospelove** [comment]
@mrowrpurr Btw it seems that this error indicates that fs watcher failed to initialize so hot reload will not work for the folder.

**Comment by mrowrpurr** [comment]
I've never seen the error happen when plugins are present, only when there
are none

**Comment by mrowrpurr** [comment]
I think my original bug report may have been wrong. It's also seen when no files, not only no directory.

**Comment by Pospelove** [comment]
no activitiy. closing ;(
