### ISSUE TITLE
Fix that containers spawned by PlaceAtMe are not lootable

### ISSUE THREAD

**Issue by alekcey0211** [skyrim-multiplayer/skymp#68]
When we create a new container, such as a barrel, with the `placeAtMe ' function, firstly, when we open it for the first time, it is empty (when you open it for the second time, there are things), secondly, if you try to take these things, you will get an error and things are not taken
```vb
	Form barrel = Game.GetFormFromFile(0x845, "Skyrim.esm")
	ObjectReference newBarrel = ac.PlaceAtMe(barrel)
	Form sword = Game.GetForm(0x12eb7)
	newBarrel.AddItem(sword)
```

I get an error like this, as if the object does not exist
```
Error in server.tick: Error: Form with id ff000d32 doesn't exist
Error: Form with id ff000d32 doesn't exist
    at ScampServer.tick (<anonymous>)
```

**Comment by Pospelove** [comment]
Closing all "temporary unsupported"
