### ISSUE TITLE
Improve readability of the codebase

### ISSUE THREAD

**Issue by Blazzes** [skyrim-multiplayer/skymp#70]
When working with code, it is very difficult to understand what this or that function or class method is responsible for, what arguments are passed in them and what they are responsible for. I would like to add at least descriptions for the function and methods with a description of the input and output parameters.

**Comment by Pospelove** [comment]
I don't think it's reasonable to check and comment on the whole codebase. Could you please specify concrete files you personally were stuck on? So, we could improve the readability of these files. If you already did some research, feel free to create a PR that adds comments.

**Comment by Blazzes** [comment]
In the IDatabase interface it is not clear what the Upsert method returns.

In the future, when expanding / adding code, difficulties may arise with the fact that it is not clear what the methods return and what they are responsible for.

**Comment by Pospelove** [comment]
Pinning this issue and keeping open for now. I`ve created a pull request adding a couple of comment lines. Feel free to open your own pull request or use this issue to leave feedback on readability:
* Missing required comments
* Bad/inconsistent files/classes/variables/methods naming
* Unclear code in general

**Comment by Pospelove** [comment]
This is impossible to finish this and no one commented so closing. Feel free to ask questions on code pieces purpose in our Discord
