### ISSUE TITLE
[Bug]: Skyrim Platform "PluginsDev" doesn't seem to do anything

### ISSUE THREAD

**Issue by DaemonIB** [skyrim-multiplayer/skymp#712]
When loading up Skyrim Platform if there's a `.js` plugin in the `PluginsDev` folder, nothing happens. If the plugin is moved to the `Plugins` folder it works as normal.

- This was using SkyrimPlatform from Nexus mods, version `2.4.0` and `2.3.0`.
- SkyrimSE version `1.5.97.0`
- SKSE version `0.2.0.20`
- Mods: `AddressLibrary v2` & `Unofficial Skyrim Special Edition Patch 4.2.4b`
- OS: Windows 10
- All mods were installed through Vortex.
- The plugin that was used when this issue occurred was the `plugin-example` plugin that comes with Skyrim Platform.

**Comment by Pospelove** [comment]
well not sure I saw this :(
plz create another issue if it's still an issue
