### ISSUE TITLE
[Bug]: Gamepad Inputs are not getting registered in SP 

### ISSUE THREAD

**Issue by duffbeeeer** [skyrim-multiplayer/skymp#714]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Gamepad DxScanCodes are not getting registered by SP atm. 

The class Input has a function isKeyPressed(dxScanCode: number), which can be used to detect If a key has been pressed. 

This works only for keyboard inputs right now, they input with gamepad codes (280+) will not get interecepted, when using the update event. 

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.08

### SKSE version

2.0.20

### client commit''s hash

-

### server commit''s hash

-

### Videocard model

2080ti

### Steps to reproduce

In the update event use if(Input.keyIsPressed(280) { printConsole('button was pressed') }

And press LT in gamepad. 

### Expected result

A console output with 'button was pressed' should appear

### Actual result

Nothing appears in the console

**Comment by Pospelove** [comment]
fixed in 2.6 after the pre-release test by the author of the issue! 🚀
