### ISSUE TITLE
Make it possible to specify a custom master server

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#742]
Need it for:
1. Client
2. Server
3. Also worth specifying the base URL in the master-api itself

**Comment by nic11** [comment]
1. Client change: #745
2. Server change: not needed, already getting custom API at `skymp5-server/ts/settings.ts:54`
3. master-api: TODO

**Comment by Pospelove** [comment]
This issue can be closed by #745 
Created a separate issue for master server
