### ISSUE TITLE
Auth breaks sync

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#749]
With login/register landed in #637 we can not interact with doors and other objects.
Seems that client starts to ignore `createActor` packets. Still works with offline mode.

**Comment by kkEngine** [comment]
Perhaps the problem is in this line https://github.com/skyrim-multiplayer/skymp/blob/a42fe771d8ee2149400345402ac3df3800b5e460/skymp5-client/src/remoteServer.ts#L296
I do not remember modifying the if condition with "&& false"

**Comment by Pospelove** [comment]
fixed by removing && false and tuning problematic syncs manually
