### ISSUE TITLE
'It seems this machine didn't compile .psc files' in unit tests

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#75]
Unit tests output two messages like this one:
```
> .\skymp5-server\cpp\Debug\unit.exe
<...>
It seems this machine didn't compile .psc files. Skipping the test
<...>
```

Triggered because directory behind preprocessor macro value `BUILT_PEX_DIR="E:/skymp/skymp/build/skymp5-server/cpp/pex/papyrus_test_files"` does not exist.

This should either be fixed by default or documented how to enable compiling these files.

**Comment by Pospelove** [comment]
Seems to be already fixed (#140 isn't). Closing for now.
