### ISSUE TITLE
Unit tests error

### ISSUE THREAD

**Issue by Blazzes** [skyrim-multiplayer/skymp#78]
![image](https://user-images.githubusercontent.com/49817628/126083021-801d75f0-a03f-4347-9291-e29d3257bd5f.png)
When running unit tests, it throws an exception. 
The "LeveledListUtilsTest.h" test is supposedly to blame.

**Comment by Pospelove** [comment]
Could you please attach stacktrace?

**Comment by Blazzes** [comment]
Could you tell me where to see attach stacktrace?

**Comment by Pospelove** [comment]
> Could you tell me where to see attach stacktrace?

In Visual Studio:
Debugger -> Attach to Process -> unit.exe

Then select `Retry` in error window

**Comment by Blazzes** [comment]
![image](https://user-images.githubusercontent.com/49817628/126084288-4bd943dd-0150-4637-a9c1-29d352f49fb7.png)

**Comment by Pospelove** [comment]
Do you have Skyrim Special Edition installed? What is your `SKYRIM_DIR`?

**Comment by Blazzes** [comment]
![image](https://user-images.githubusercontent.com/49817628/126127001-23bdd345-a6dd-4ba2-8ff6-1f90f82056cf.png)

**Comment by Pospelove** [comment]
@Blazzes 

Throws here:
https://github.com/skyrim-multiplayer/skymp/blob/6f105644eb557a7f9f80199682d7ef2463e6b81e/skymp5-server/cpp/lib_espm/Loader.h#L108

Could you debug this and say what's the value of the `dataDir` variable is here?
After that, go checking that this path exists.

**Comment by Blazzes** [comment]
I don't know what happened, but it worked.

**Comment by Pospelove** [comment]
Feel free to reopen/open a new issue if the error is still here. Closing for now
