### ISSUE TITLE
[Bug]: Actor.hasLos crashes the game

### ISSUE THREAD

**Issue by kkEngine** [skyrim-multiplayer/skymp#786]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

A bug happened in 80% calls once("update") with random actor

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

0a4df5dcd4c853ddd02541e9f59255957fde0ebf

### server commit''s hash

0a4df5dcd4c853ddd02541e9f59255957fde0ebf

### Videocard model

unknown

### Steps to reproduce

call hasLos function on a player actor

### Expected result

no game crash

### Actual result

The game crashes

**Comment by duffbeeeer** [comment]
I can confirm this issue partly. I am using actor.hasLOS(player) in DBC without issue. But using player.hasLOS(actor) will crash the game.
