### ISSUE TITLE
[Bug]: "actionBeginDraw" Buggy.

### ISSUE THREAD

**Issue by objir** [skyrim-multiplayer/skymp#795]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Weapon sheathing doesn't work properly after using the event.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.08

### SKSE version

2.0.20

### client commit''s hash

9a4bb6b55f84559b35e4998ec5737ed5e94ee1c1

### server commit''s hash

N/A

### Videocard model

RTX 2060

### Steps to reproduce

Use "actionBeginDraw" event on player character.

### Expected result

After the event the weapon should be able to be sheathed properly.

### Actual result

The weapon equipped (one-handed in the right hand mostly) remains in the player's hand aftering sheathing it. Repeat drawing-sheathing the weapon again makes the player invisible. 
If using this event with "Mu Joint Fix (Knee Fix dll edition):[https://www.nexusmods.com/skyrimspecialedition/mods/61479?tab=files](url)" activated, the game crashes. A log: https://pastebin.com/XtGcqWZQ.

**Comment by objir** [comment]
Same issue happens to "actionBeginSheathe" as well.

**Comment by Pospelove** [comment]
@objir Could you please attach your TypeScript code that reproduces the problem?

**Comment by objir** [comment]
Can "actionBeginDraw" be used alone or is it essential to use "actionEndDraw" along with it? There is no issue if I use both at the same time.

<details>
  <summary>ucswingeffect.ts</summary>

import { on, Spell, Game, printConsole } from 'skyrimPlatform'


function ApplyEffect(){
    const player = Game.getPlayer()
    const aaaUCSwingShortSpell = Game.getFormFromFile(0x80A,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingSpell = Game.getFormFromFile(0x80B,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingLeftSpell = Game.getFormFromFile(0x808,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingShortLSpell = Game.getFormFromFile(0x809,"UltimateCombatSwingEffect.esp") as Spell
    const weaptypeR = player!.getEquippedItemType(1)
    const weaptypeL = player!.getEquippedItemType(0)
    if(weaptypeR == 2){
        player!.addSpell(aaaUCSwingShortSpell,false)
    }
    else if(weaptypeR <= 6 && weaptypeR != 0){
        player!.addSpell(aaaUCSwingSpell,false)
    }
    if(weaptypeL == 2){
        player!.addSpell(aaaUCSwingShortLSpell,false)
    }
    else if(weaptypeL <= 4 && weaptypeL != 0){
        player!.addSpell(aaaUCSwingLeftSpell,false)
    }
}

function RemoveEffect(){
    const player = Game.getPlayer()
    const aaaUCSwingShortSpell = Game.getFormFromFile(0x80A,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingSpell = Game.getFormFromFile(0x80B,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingLeftSpell = Game.getFormFromFile(0x808,"UltimateCombatSwingEffect.esp") as Spell
    const aaaUCSwingShortLSpell = Game.getFormFromFile(0x809,"UltimateCombatSwingEffect.esp") as Spell
    if (player!.hasSpell(aaaUCSwingSpell)){
        player!.removeSpell(aaaUCSwingSpell)
    }
    else if (player!.hasSpell(aaaUCSwingShortSpell)){
        player!.removeSpell(aaaUCSwingShortSpell)
    }
    if (player!.hasSpell(aaaUCSwingLeftSpell)){
        player!.removeSpell(aaaUCSwingLeftSpell)
    }
    else if (player!.hasSpell(aaaUCSwingShortLSpell)){
        player!.removeSpell(aaaUCSwingShortLSpell)
    }
}

on("actionWeaponSwing", (event) => {
    if(event.actor == Game.getPlayer()){
        ApplyEffect()
    }
})

on("actionBeginDraw", (event) => {
    if(event.actor == Game.getPlayer()){
        RemoveEffect()
        ApplyEffect()
    }
})

</details>

**Comment by Pospelove** [comment]
probably will be fixed by #653

**Comment by objir** [comment]
esp: https://drive.google.com/file/d/1-WiVsFgBji1IjTbyAE5BkVeb4ycJkNxN/view?usp=sharing

It use meshes and textures from ultimate combat se.

**Comment by objir** [comment]
Well, the symptoms of the issue are from the ultimate combat behavior files. After rewriting the ts plugin to make sure the spells are removed before Weapon Sheathing ends, the issue is gone. Sorry, my bad.
