### ISSUE TITLE
Update vcpkg once mongo-related warnings are fixed

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#80]
Project files generation always emits warnings.  Should fix them:

Update vcpkg submodule to latest once https://github.com/microsoft/vcpkg/pull/18751 is merged

```cmake
CMake Warning at build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/bson-1.0/bson-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::bson_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/bson-1.0/bson-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::bson_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/bson-1.0/bson-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::bson_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)


CMake Warning at build/vcpkg_installed/x64-windows-sp/share/bson-1.0/bson-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::bson_static' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  build/vcpkg_installed/x64-windows-sp/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  skymp5-server/cpp/CMakeLists.txt:173 (find_package)
```

**Comment by sherlok235** [comment]
**I also  have received something similar**



`

> CMake Warning at cmake/add_papyrus_library_ck.cmake:37 (message):
>   Missing Papyrus Compiler at OFF/Papyrus compiler/PapyrusCompiler.exe.
>   Target skymp5-scripts wouldn't be built
> Call Stack (most recent call first):
>   skymp5-scripts/CMakeLists.txt:5 (add_papyrus_library_ck)
> 
> 
> CMake Warning at skymp5-server/cpp/CMakeLists.txt:114 (message):
>   SKYRIM_DIR is not specified, Papyrus sources will not be built
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::bson_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::bson_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::bson_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::mongoc_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> CMake Warning at build/vcpkg_installed/x64-linux/share/libbson-1.0/libbson-1.0-config.cmake:15 (message):
>   This CMake target is deprecated.  Use 'mongo::bson_static' instead.
>   Consult the example projects for further details.
> Call Stack (most recent call first):
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   build/vcpkg_installed/x64-linux/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
>   vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
>   skymp5-server/cpp/CMakeLists.txt:188 (find_package)
> 
> 
> info TOOL Using Ninja generator, because ninja is available.
> info CMD CONFIGURE
> `

**Comment by nic11** [comment]
@sherlok235 See #140

**Comment by Pospelove** [comment]
The problem still exists in main branch
