### ISSUE TITLE
[Bug]: Skyrim Platform causing a CTD when Trying to sell an Equipped Iron Spear to NPC

### ISSUE THREAD

**Issue by ixanza** [skyrim-multiplayer/skymp#848]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

One of my users tried selling an equipped Iron spear to Belethor and it caused an instant CTD. The Netscriptframework log says the crash happened inside the SkyrimPlatform DLL so I'm hoping you guys have some insight on whats causing this

https://ghostbin.com/oPWvj

### OS

Windows

### OS version

11

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

N/A

### server commit''s hash

N/A

### Videocard model

N/A

### Steps to reproduce

Equip weapon, sell weapon

### Expected result

item sells fine

### Actual result

crash

**Comment by Pospelove** [comment]
please reopen if still an issue

I'm not sure if it works now or not. i couldn't reproduce

we could fix that. sorry for not answering in time
