### ISSUE TITLE
Chat escaping issues

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#912]
We need a rework of chat message escaping.

- [ ] Chat messages containing apostrophes don't show up
- [ ] `/` is being replaced by `undefined`

**Comment by russo-2025** [comment]
https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-functions-lib/src/props/chatProperty.ts#L54

**Comment by nic11** [comment]
Actually I think this one requires more than just changing regexp. So we should solve this problem not by just removing `'`, but by actually properly escaping everything. So some more testing should be involved here.

**Comment by russo-2025** [comment]
нужно как минимум добавить недостающие символы из регулярки в массив
