### ISSUE TITLE
Deploy every day at 5:00

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#916]

**Comment by nic11** [comment]
Nonono, not a solution. Unless it's about indev

**Comment by Pospelove** [comment]
¯\_(ツ)_/¯ good luck always running outdated server because no one deploys it

**Comment by nic11** [comment]
@Pospelove Prod server should be deployed after changes are tested on pre-prod (or testing), not automatically, even if it's merged. We have commits that shouldn't go to prod **right now.** It's better to do it manually

**Comment by Pospelove** [comment]
@nic11 What are the commits you are talking about?

**Comment by nic11** [comment]
@Pospelove For example this one:
https://github.com/skyrim-multiplayer/skymp/commit/a9a992a82717207c0d1b6ec2d220abc1fee04560

This adds maps, but we need to update `esp` on server and clients for that. So this requires #118

**Comment by Pospelove** [comment]
@nic11 maps are disabled by enabled: false flag

**Comment by Pospelove** [comment]
Except markarth
