### ISSUE TITLE
[minor] Animations don't stop when player begins moving in 1st-person view

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#922]
> Классический полет в анимации сидения и лежания от первого лица. Конкретно у вас это медитация и лежание в стартовой локации

https://discord.com/channels/699653182946803722/938471682706923601/938527731652636692

**Comment by Pospelove** [comment]
We need to force 3-rd person view for this case

**Comment by Pospelove** [comment]
seems to be fixed these days
