### ISSUE TITLE
[minor] Broken tail of the current player

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#929]
If you enter 3rd person view while playing a race which has a tail, it is broken

Report: https://discord.com/channels/699653182946803722/938471682706923601/938877693611638784

Screenshots:
- https://cdn.discordapp.com/attachments/938471682706923601/938877692701466624/20220203212100_1.jpg
- https://cdn.discordapp.com/attachments/938471682706923601/938879339095789618/20220203212857_1.jpg

**Comment by Pospelove** [comment]
not fixed but added to roadmap https://github.com/skyrim-multiplayer/skymp/pull/1084
