### ISSUE TITLE
[Bug]: remoteIdToLocalId

### ISSUE THREAD

**Issue by russo-2025** [skyrim-multiplayer/skymp#931]
### Severity

Minor. A minor defect that doesn''t violate the application''s functionality when tested, but influences the expected result. A design error wobe one example. A bug that doesn't affect the functionality or operation of the app but can be detected visually, for example, a typo in the text.

### Priority

Low. All else (typos, missing icons, layout issues, etc.).

### Description

почему если в `remoteIdToLocalId` передать твой серверный id (например 0xFF000000) то он вернет id твоей копии(`show-me`) или 0

why if you pass your server id to `remoteIdToLocalId` (for example 0xFF000000) then it will return the id of your copy(`show-me`) or 0

### OS

windows

### OS version

10

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

accdd216256b21083b2c22a1cc0c146db13a0a29

### server commit''s hash

accdd216256b21083b2c22a1cc0c146db13a0a29

### Videocard model

100500

### Steps to reproduce

A bug happened!

### Expected result

`Game.getPlayer().getFormId()` aka `0x14`

### Actual result

id of your copy(`show-me`) or 0

**Comment by Pospelove** [comment]
I am not sure that it is a bug

**Comment by Pospelove** [comment]
Actually this behavior is expected
