### ISSUE TITLE
Implement kill command

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#934]

**Comment by SupAidmi** [comment]
if a player enters the command /kill in the chat, then we kill him. This is necessary so that the player can spawn in the hub if he gets stuck somewhere.

**Comment by nic11** [comment]
When players sends a chat message, it's being handled this way:
* https://github.com/skyrim-multiplayer/skymp/blob/1165013c981c633ff45e1e9bf7c3ad85e4101b30/skymp5-functions-lib/src/props/chatProperty.ts#L35
* https://github.com/skyrim-multiplayer/skymp/blob/1165013c981c633ff45e1e9bf7c3ad85e4101b30/skymp5-functions-lib/src/mpApiInteractor.ts#L91
* https://github.com/skyrim-multiplayer/skymp/blob/1165013c981c633ff45e1e9bf7c3ad85e4101b30/skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts#L199

We want to intercept it if it is `/kill` and set the player's health to 0:
https://github.com/skyrim-multiplayer/skymp/blob/1165013c981c633ff45e1e9bf7c3ad85e4101b30/skymp5-functions-lib/src/logic/PlayerController.ts#L20

That should hopefully work well (alternatively explicitly call something that would kill the player)
