### ISSUE TITLE
Write console contents (and other logs) to a file

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#938]
_For reference: listening for console output from SkyrimPlatform TS plugins is already available, see https://github.com/skyrim-multiplayer/skymp/blob/main/docs/release/sp-2.2.md#add-consolemessage-event for details._

Events are being sent from C++ to TS here:
https://github.com/skyrim-multiplayer/skymp/blob/46aeeb929222a5ce6fcdfd69cd1d88225684de34/skyrim-platform/src/platform_se/skyrim_platform/EventsApi.cpp#L493

And this is the code that actually captures them:
https://github.com/skyrim-multiplayer/skymp/blob/46aeeb929222a5ce6fcdfd69cd1d88225684de34/skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp#L135

**General task**
In this issue, we should received console log lines write to a file (not directly! we don't want to slow the game down). SKSE already stores its log files in `%USERPROFILE%/Documents/My Games/Skyrim Special Edition/SKSE/`. We can place our console log to something like `%USERPROFILE%/Documents/My Games/Skyrim Special Edition/Platform/<start_time>.log`.

**spdlog**
see docs

<details>
<summary>Old variant</summary>
**Multithreading**
The resulting approach should be multithreaded: we don't want to slow game threads down. From my point of view, we can add an FS task queue here:
https://github.com/skyrim-multiplayer/skymp/blob/46aeeb929222a5ce6fcdfd69cd1d88225684de34/skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp#L314
And then create method `void SkyrimPlatform::WriteLog(const std::string&)` which adds an FS task to write a new log line like this:
```c++
  this->AddFsTask([=] {
    // !!!         vvvvvvv   this MUST NOT be const char*, but something copyable like std::string
    g_spLogFile << logLine << std::endl;
  });
```
</details>

**Comment by Pospelove** [comment]
Merged AE branch which already has support for that.
