### ISSUE TITLE
Papyrus vm cant properly handle ObjectReference or ObjectReference[] from script properties

### ISSUE THREAD

**Issue by Wedmer** [skyrim-multiplayer/skymp#941]
When using `self` object all functions work, when passed to js we get `{"type":"form","desc":"4c3644:SweetPie.esp"}`
Same when using `Game.GetForm(int)`
When using item from script property  none of functions work, when passed to js we get  `{"type":"espm","desc":"4c3644:SweetPie.esp"}`

**Comment by Pospelove** [comment]
fixed in modern versions. reopen if still an issue.
