### ISSUE TITLE
[Bug]: The quantity of "Gold001" (0000000F) is not displayed correctly in the inventory.

### ISSUE THREAD

**Issue by SupAidmi** [skyrim-multiplayer/skymp#997]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

The quantity of "Gold001" (0000000F) is not displayed correctly in the inventory. When receiving a reward in the form of coins, they are not displayed in the coin counter in the inventory. Also, when buying pies, the taken coins are not displayed in the coin counter in the inventory. At the same time, it is in the player's inventory, you can check it by buying or selling something.

### OS

Windows

### OS version

10

### Skyrim version

1.5,97,08

### SKSE version

2.0.20

### client commit''s hash

df63ebd83a2137064f4373d92fbee6a50f6ef75a

### server commit''s hash

df63ebd83a2137064f4373d92fbee6a50f6ef75a

### Videocard model

RX 470

### Steps to reproduce

1. Look at the amount of gold in your inventory
2. Buy a pie or sell an ingot
3. Open the inventory again

### Expected result

The amount of gold has changed

### Actual result

The amount of gold has not changed

**Comment by Pospelove** [comment]
Seems to be fixed. Please reopen if it is still an issue
